# 可以尝试集成config-server来配置

spring:
  application:
    name: platform-gateway
  redis:
    host: localhost
    port: 6379
    database: 0
  main:
    allow-bean-definition-overriding: true
  # 链路追踪
  zipkin:
    base-url: http://ZIPKIN-SERVER/
    discovery-client-enabled: true
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      probability: 1
  # 跨域配置
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # 返回的资源共享给请求来源
            allowed-origins:
            - "http://localhost:8080"
            - "http://101.200.229.14:8080"
            - "http://101.200.229.14"
            - "*"
            # 比如cookie, authorization之类的认证信息
            allow-credentials: true
            allowed-headers: "*"
            allowed-methods: "*"
            expose-headers: "*"
            # 表示Options可以在浏览器缓存多长时间
            max-age: 600
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
#        routes:

server:
  port: 20004

eureka:
  client:
    serviceUrl:
      defalutZone: http://localhost:20000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  security:
    enabled: false