server:
  port: 20000
  # spring boot 2.3.X和2.2.X的一个异常处理的改动
  error:
    include-exception: true
    include-stacktrace: on_param
    include-message: always


spring:
  application:
    name: restroom-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/toilet_db?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: zhoukuo
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      connection-timeout: 20000
      idle-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 30000
      auto-commit: true
      pool-name: DatasourcePool


management:
  endpoints:
    web:
      exposure:
        # 暴露所有endpoint
        include: '*'
  endpoint:
    health:
      # 总是显示各个组件的actuator信息
      show-details: always
  security:
    enabled: false
