###############################################
#
# Eureka????
#
###############################################
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

server:
  port: 20001
management:
  server:
    port: 52001

spring:
  application:
    name: hystrix-turbine
turbine:
  aggregator:
    cluster-config: default
  app-config: foodie-order-service
  #  app-config: foodie-user-service,foodie-item-service,foodie-order-service
  # ?????default
  cluster-name-expression: '"default"'
  # ??Host + Port ??????????
  combine-host-port: true
  # ???actuator???????????
  instanceUrlSuffix:
    default: actuator/hystrix.stream



