# 极简配置

dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper
    # 启动时检查是否存在, 注册中心不存在就报错
    check: false
  # dubbo-admin 配置
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  monitor:
    # 用于配置连接监控中心相关信息, 可选
    protocol: register
  consumer:
    # 启动时检查服务提供者是否存在, 不存在就报错
    check: false
    timeout: 3000

server:
  port: 63000
