spring:
  application:
    name: sleuth-traceB
  sleuth:
    sampler:
      probability: 1
  # zipkin 的地址
  zipkin:
    base-url: http://localhost:62100
server:
  port: 62001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

logging:
  file: ${spring.application.name}.log

info:
  app:
    name: sleuth-traceB
    description: test

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
