server:
  port: 10003

spring:
  datasource:
    # 拆分数据源到独立database instance, 或者独立schema
    # url: jdbc:mysql://localhost:3306/foodie-cloud-item?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    password: zhoukuo
  redis:
    # redis 单机单实例
    database: 0
    host: localhost
    port: 6379
    password: zhoukuo

    # redis 哨兵模式
    #    database: 1
    #    password: zhoukuo
    #    sentinel:
    #      master: my-master
    #      nodes: 192.168.1.191:26379, 192.168.1.192:26379, 192.168.1.193:26379

    # redis 集群模式
#    password: zhoukuo
#    cluster:
#      nodes: 192.168.1.201:6379, 192.168.1.202:6379, 192.168.1.203:6379, 192.168.1.204:6379, 192.168.1.205:6379, 192.168.1.206:6379
####################################################################################
# Stream配置
####################################################################################
  cloud:
    stream:
      bindings:
        orderstatus-consumer:
          destination: orderstatus-topic
          group: order-group
        orderstatus-producer:
          destination: orderstatus-topic
      rabbit:
        bindings:
          orderstatus-producer:
            producer:
              delayed-exchanged: true


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# Ribbon全局配置
ribbon:
  ConnectTimeout: 1000  # 建立连接的用时
  ReadTimeout: 3000     # 获取响应的用时

# Ribbon指定服务配置超时判定, 优先级更高
foodie-user-service:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    OkToRetryOnAllOperations: true

# Feign的超时判定, 优先级高于Ribbon
feign:
  hystrix:
    enabled: true
  client:
    config:
      # 全局默认配置
      defalut:
        connectTimeout: 1000
        readTimeout: 5000
      foodie-user-server:
        connectTimeout: 1000
        readTimeout: 5000

### 开启所有actuator-endpoint
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  #        include: health, info, xxx
  security:
    enabled: false

hystrix:
  command:
    # 有的属性是默认值, 写不写都行
    default:
      fallback:
        enabled: true
      circuitBreaker:
        enabled: true
        # 超过50%错误, 那么开启熔断
        errorThresholdPercentage: 50
        # 当5个request之后才进行统计
        requestVolumeThreshold: 5
        # 10s之后进入半开状态
        sleepWindowInMilliseconds: 10000
        # forceClosed, forceOpen 强制关闭/开启熔断开关
      execution:
        timeout:
          enabled: true
        # 可以指定隔离方式线程池还是信号量
        isolation:
          thread:
            interruptOnTimeout: true
            interruptOnFutureCancel: true
            timeoutInMilliseconds: 10000
      metrics:
        rollingStats:
          # 时间窗口统计
          timeInMilliseconds: 20000


