spring:
  application:
    name: stream-sample
  # RabbitMQ连接字符串
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
  # 绑定 Channel 到 broadcast
  cloud:
    stream:
      bindings:
        myTopic-consumer:
          destination: broadcast
        myTopic-producer:
          destination: broadcast

        # 异常消息(单机版重试)
        error-consumer:
          destination: error-out-topic
          # 重试次数(客户端消费者本机重试, 而不是重新把消息发回给rabbitmq)
          # 次数=1相当于不重试
          consumer:
            max-attempts: 2
        error-producer:
          destination: error-out-topic

        ### 延迟消息配置
        delayed-consumer:
          destination: delayed-topic
        delayed-producer:
          destination: delayed-topic
      # 定义 delayed 类型的 exchange
      rabbit:
        bindings:
          delayed-producer:
            producer:
              delayed-exchange: true
        # 消息分组示例
        group-consumer:
          destination: group-topic
          group: Group-A
          ## 打开消费者的消费分区功能
          consumer:
            partitioned: true
        group-producer:
          destination: group-topic
          ## 消费分区配置, 两个消息分区
          producer:
            partition-count: 2
            # SpEL(Key resolver)
            # 只有索引参数为1的节点(消费者), 才能消费消息
            partition-key-expression: 1
      ## 当前消费者实例总数
      instance-count: 2
      ## 最大值instanceCount-1, 当前实例的索引号
      instance-index: 0








server:
  port: 63000


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
