spring:
  application:
    name: stream-sample
  # RabbitMQ连接字符串
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    ##########  默认全局开启 异常消息 requeue 重试
#    listener:
#      direct:
#        default-requeue-rejected: true
  main:
    allow-bean-definition-overriding: true
  # 绑定 Channel 到 broadcast
  cloud:
    stream:
      bindings:
        myTopic-consumer:
          destination: broadcast
        myTopic-producer:
          destination: broadcast

        # 异常消息(单机版重试)
        error-consumer:
          destination: error-out-topic
          # 重试次数(客户端消费者本机重试, 而不是重新把消息发回给rabbitmq)
          # 次数=1相当于不重试
          consumer:
            max-attempts: 2
        error-producer:
          destination: error-out-topic

        # 异常消息(requeue 重试)
        requeue-consumer:
          destination: requeue-topic
          group: requeue-group
          ## 仅对当前requeue-consumer, 开启requeue重试
          consumer:
            requeueRejected: true
            # 必须把max-attempts设置为1, 否则requeue不能生效
            max-attempts: 1
        requeue-producer:
          destination: requeue-topic

        # 死信队列配置
        dlq-consumer:
          destination: dlq-topic
          group: dlq-group
          consumer:
            ## 尝试次数
            max-attempts: 2
        dlq-producer:
          destination: dlq-topic

        # Fallback配置
        fallback-consumer:
          destination: fallback-topic
          group: fallback-group
          consumer:
            ## 尝试次数
            max-attempts: 2
        fallback-producer:
          destination: fallback-topic


        ### 延迟消息配置
        delayed-consumer:
          destination: delayed-topic
        delayed-producer:
          destination: delayed-topic
      # 定义 delayed 类型的 exchange
      rabbit:
        bindings:
          delayed-producer:
            producer:
              delayed-exchange: true
          ### 开启死信队列 (默认 topic.dlq)
          dlq-consumer:
            consumer:
              auto-bind-dlq: true
        # 消息分组示例
        group-consumer:
          destination: group-topic
          group: Group-A
          ## 打开消费者的消费分区功能
          consumer:
            partitioned: true
        group-producer:
          destination: group-topic
          ## 消费分区配置, 两个消息分区
          producer:
            partition-count: 2
            # SpEL(Key resolver)
            # 只有索引参数为1的节点(消费者), 才能消费消息
            partition-key-expression: 1
      ## 当前消费者实例总数
      instance-count: 2
      ## 最大值instanceCount-1, 当前实例的索引号
      instance-index: 0




server:
  port: 63000


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
