spring:
  application:
    name: auth-service
  redis:
    database: 0
    host: localhost
    port: 6379

server:
  port: 65100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka

logging:
  file: ${spring.application.name}.log

info:
  app:
    name: auth-service
    description: test

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false