server:
  port: 10002

spring:
  datasource:
  # 拆分数据源到独立database instance, 或者独立schema
    # url: jdbc:mysql://localhost:3306/foodie-cloud-item?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/foodie-shop-dev?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
#    password: zhoukuo
    url: ${mariadb.url}
    password: ${mariadb.password}
  redis:
    # redis 单机单实例
    database: 0
    host: localhost
    port: 6379
    password: zhoukuo

    # redis 哨兵模式
    #    database: 1
    #    password: zhoukuo
    #    sentinel:
    #      master: my-master
    #      nodes: 192.168.1.191:26379, 192.168.1.192:26379, 192.168.1.193:26379

    # redis 集群模式
#    password: zhoukuo
#    cluster:
#      nodes: 192.168.1.201:6379, 192.168.1.202:6379, 192.168.1.203:6379, 192.168.1.204:6379, 192.168.1.205:6379, 192.168.1.206:6379


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


### 开启所有actuator-endpoint
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: '*'
##        include: health, info, xxx
#  security:
#    enabled: false

hystrix:
  command:
    # 有的属性是默认值, 写不写都行
    default:
      fallback:
        enabled: true
      circuitBreaker:
        enabled: true
        # 超过50%错误, 那么开启熔断
        errorThresholdPercentage: 50
        # 当5个request之后才进行统计
        requestVolumeThreshold: 5
        # 10s之后进入半开状态
        sleepWindowInMilliseconds: 10000
        # forceClosed, forceOpen 强制关闭/开启熔断开关
      execution:
        timeout:
          enabled: true
        # 可以指定隔离方式线程池还是信号量
        isolation:
          thread:
            interruptOnTimeout: true
            interruptOnFutureCancel: true
            timeoutInMilliseconds: 10000
      metrics:
        rollingStats:
          # 时间窗口统计
          timeInMilliseconds: 20000
#          numBuckets: 10
#        rollingPercentile:
#          timeInMilliseconds: 20000
#          numBuckets: 10
#          bucketSize: 300
    # 照这个方法, 覆盖其他的属性
    loginFail:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000














